import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Button from '@mui/material/Button';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>الحاوية | Container</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button variant="text" className="md:bg-red-700 sm:bg-blue-700" color="primary">
          s
        </Button>
        <p className={styles.description}>
         by{' '}
          <code className={styles.code}>BeeMedia</code>
        </p>
      </main>
    </div>
  )
}
