import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>الحاوية | Container</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Container!</a>
        </h1>
        <p className={styles.description}>
         by{' '}
          <code className={styles.code}>BeeMedia</code>
        </p>
      </main>
    </div>
  )
}
